apiVersion: v1
kind: Secret
metadata:
  name: bank-admin-secret
  namespace: bank-domain-ns
type: Opaque
data:
  username: d2VibG9naWM=
  password: V2VsY29tZTEyMw==

---

apiVersion: v1
kind: Secret
metadata:
  name: bank-db-secret
  namespace: bank-domain-ns
type: Opaque
data:
  username: YmFua3VzZXI=
  password: QmFua1Bhc3N3b3JkMTIz

---
apiVersion: v1
kind: Secret
metadata:
  name: bank-runtime-encryption-secret
  namespace: bank-domain-ns
type: Opaque
data:
  password: d2VsY29tZTEyM0k=

