apiVersion: v1
kind: PersistentVolume
metadata:
  name: bank-domain-pv
spec:
  storageClassName: manual
  capacity:
    storage: 3Gi  # Size of the disk pool
  accessModes:
    - ReadWriteMany  # Allows multiple managed servers to read/write at the same time
  persistentVolumeReclaimPolicy: Retain  # Keep data safe even if the domain is deleted
  hostPath:
    path: "/data/bank-storage"  # The real folder path inside your Minikube machine

